Retry logic for 202
FlipsideCrypto/crosschain-models pull request #195
Opened 2023-10-04 18:34 UTC by WHYTEWYLL

2023-10-11 13:12 UTC, eric-laurello commented on .github/workflows/dbt_dev_general_weekly.yml
> +    - cron: "10 * * * 6" # 10 minutes past the hour, every hour, on Sunday
this is set to run once on  Saturday: https://crontab.guru/#10_*_*_*_6

2023-10-11 16:17 UTC, desmond-hui requested changes

2023-10-12 12:37 UTC, WHYTEWYLL commented on .github/workflows/dbt_dev_general_weekly.yml
> +    - cron: "10 * * * 6" # 10 minutes past the hour, every hour, on Sunday
The comment is wrong, it should be on Satruday.

2023-10-12 12:38 UTC, WHYTEWYLL commented on macros/api_udf/request_repo_data.sql
> +CREATE OR REPLACE TABLE {{ target.database }}.bronze_api.log_messages (
Good catch

2023-10-12 13:55 UTC, desmond-hui commented on macros/api_udf/request_repo_data.sql
> +}
Still not sure of the overall intent of this code. If the goal is to stop retrying endpoints with `>5 retries` in the current run of the stored procedure then the `last_time_queried` value would need to be updated as well. If that is not the goal, then this block is fine as is.

2023-10-12 13:56 UTC, desmond-hui approved these changes

2023-10-12 14:49 UTC, WHYTEWYLL commented on macros/api_udf/request_repo_data.sql
> +}
Nop, thats not the case. Its just a way to send them down on the table. And so we try later with a smaller lambda size.

2023-11-03 13:27 UTC, merged