add flow labels for tokens and nfts
FlipsideCrypto/crosschain-models pull request #389
Opened 2024-10-01 19:47 UTC by gronders

adding token labels from tokenlist and scan

2024-10-03 18:23 UTC, forgxyz requested changes

2024-10-03 18:23 UTC, forgxyz commented on models/silver/labels/contract_autolabel/flow_evm/silver__flow_evm_fs_token_labels.sql
> +            'https://evm.flowscan.io/api/v2/tokens?items_count=1000'
API limits response to 50 and I am struggling to paginate through it at the moment

2024-10-03 18:31 UTC, forgxyz commented on models/silver/labels/contract_autolabel/flow_evm/silver__flow_evm_fs_token_labels.sql
> +    DISTINCT SYSDATE() AS system_created_at,
distinct and sysdates

2024-10-03 18:31 UTC, forgxyz commented on models/silver/labels/contract_autolabel/flow_evm/silver__flow_evm_fs_token_labels.yml
> +            - ADDRESS
unique test

2024-10-07 16:17 UTC, gronders commented on models/silver/labels/contract_autolabel/flow/silver__flow_nft_labels.sql
> +        VALUE :chainId AS chainId,
fixed

2024-10-07 16:18 UTC, gronders commented on models/silver/labels/contract_autolabel/flow/silver__flow_nft_labels.sql
> +        DISTINCT LOWER(CONCAT('A.', token_address_trim, project_name)) AS address,
good catch, fixed

2024-10-07 16:19 UTC, gronders commented on models/silver/labels/contract_autolabel/flow/silver__flow_nft_labels.sql
> +        address != '0xe452a2f5665728f5'
RE: slack thread. 
Its a user's address getting flagged as a token creater because he launched a token from his base address

2024-10-07 16:21 UTC, gronders commented on models/silver/labels/contract_autolabel/flow/silver__flow_nft_labels.sql
> +    DISTINCT SYSDATE() AS system_created_at,
usually its dates for when the contract was created, when it was inserted into our data, when it was labeled, and if we ever modified it. 
API doesn't have the contract deploy dates and such, so its all just sysdate(). 
Essentially matching the date structure of all the other sources of labels.

2024-10-07 16:25 UTC, gronders commented on models/silver/labels/contract_autolabel/flow/silver__flow_nft_labels.sql
> +    SYSDATE() AS _inserted_timestamp,
matches the structure of other labels files

2024-10-07 16:31 UTC, gronders commented on models/silver/labels/contract_autolabel/flow_evm/silver__flow_evm_nft_labels.sql
> +        livequery.live.udf_api(
I dont know what you are asking

2024-10-07 16:32 UTC, gronders commented on models/silver/labels/contract_autolabel/flow/silver__flow_token_labels.sql
> +        live.udf_api('https://raw.githubusercontent.com/fixes-world/token-list-jsons/refs/heads/main/jsons/mainnet/flow/default.json') AS rawoutput
doesn't work with that

2024-10-07 16:35 UTC, gronders commented on models/silver/labels/silver__contract_autolabels.sql
>    incremental_strategy = 'delete+insert',
what would you recommend? 
I know there isn't incremental logic, but wouldn't this persist token labels that on the off chance were dropped from source, but we loaded it before it was dropped? 
Would agree that 99% will be rewrite

2024-10-07 23:25 UTC, forgxyz commented on models/silver/labels/contract_autolabel/flow/silver__flow_nft_labels.sql
> +        address != '0xe452a2f5665728f5'
Ah, 💎

2024-10-08 16:21 UTC, gronders commented on models/silver/labels/contract_autolabel/flow_evm/silver__flow_evm_fs_token_labels.sql
> +            'https://evm.flowscan.io/api/v2/tokens?items_count=1000'
delted file

2024-10-11 20:51 UTC, forgxyz commented on models/silver/labels/contract_autolabel/flow_evm/silver__flow_evm_nft_labels.sql
> +        livequery.live.udf_api(
This model is evm nfts, but we are pulling down the flow mainnet json file
`https://raw.githubusercontent.com/fixes-world/token-list-jsons/refs/heads/main/nftlist-jsons/mainnet/flow/default.json`
vs the evm one
`https://github.com/fixes-world/token-list-jsons/blob/main/nftlist-jsons/mainnet/evm/default.json`

2024-10-11 20:51 UTC, forgxyz commented on models/silver/labels/contract_autolabel/flow_evm/silver__flow_evm_nft_labels.sql
> +        livequery.live.udf_api(
https://github.com/fixes-world/token-list-jsons/tree/main/nftlist-jsons/mainnet

2024-10-11 20:52 UTC, forgxyz commented on models/silver/labels/contract_autolabel/flow/silver__flow_token_labels.sql
> +        live.udf_api('https://raw.githubusercontent.com/fixes-world/token-list-jsons/refs/heads/main/jsons/mainnet/flow/default.json') AS rawoutput
Hmm, it was failing without it on my run.
The others have it, was just this one failing with the db indicator?

2024-10-11 21:12 UTC, forgxyz approved these changes

2024-10-11 21:13 UTC, merged